#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/lib/neuron/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/marder/code/simulation-environment-paper/neuron/x86_64/.libs/libnrnmech.so" "$@"
